### ISSUE TITLE
It´s not a issue at all

### ISSUE THREAD

**Issue by Diego-JRH** [Touched/MegaEvolution#26]
I din´t konw how to contact with Touched for some information so I commented here. My issue is the following : I want a metod to port the Touched megaevolution system to other fire red rom base (like BPRS). I think this won't be difficult because is still fire red. I think that only the the pointers have to be changed but I'm not sure. Waiting for answer please.

Thanks anyway

**Comment by Touched** [comment]
The other European language versions are essentially identical to English FireRed, so all you should need to do is change the symbols (pointers) in the BPRE.sym file to the correct locations in your target ROM. This is a tedious task, but it should be relatively easy. You can use an IDA plugin called bindiff to import the symbol names from knizz's BPRE IDB into a blank BPRS IDB. Since I kept the symbol names pretty similar (if not identical) to knizz's names, you should be able to match most of the addresses automatically.

If you should manage to successfully port the symbols, please make a pull request with your changes so other people can use them.
